(load "shapes.scm")
(perform "print" "shapes.dat")
(newline)
(perform "count" "shapes.dat")
(newline)
(perform "min" "shapes.dat")
(newline)
(perform "max" "shapes.dat")
(newline)
(perform "total" "shapes.dat")
(newline)
(perform "avg" "shapes.dat")
(newline)
(perform "print" "shapes.dat" "type" "==" "cuboid" "area" ">=" 88)
(newline)
(perform "count" "shapes.dat" "type" ">" "cyl")
(newline)
(perform "count" "shapes.dat" "type" "!=" "cuboid")